from django.contrib import admin
from Home.models import*
# Register your models here.
admin.site.register(brain)
admin.site.register(beginner)
admin.site.register(brute)
admin.site.register(greed)
admin.site.register(sub)
admin.site.register(implement)
admin.site.register(sort)
admin.site.register(binary)
admin.site.register(pointer)
admin.site.register(hash)
admin.site.register(pair)
admin.site.register(dpstand)
admin.site.register(dp)
admin.site.register(tree)
admin.site.register(graph)
admin.site.register(dsu)
admin.site.register(segtree)
admin.site.register(recursion)
admin.site.register(mixed)
admin.site.register(add)
admin.site.register(bit)
admin.site.register(GlobalVariable)