# Generated by Django 3.2.19 on 2023-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20230705_0953'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='recursion',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('order', models.CharField(default='1', max_length=20)),
    #             ('name', models.CharField(max_length=30)),
    #             ('description', models.TextField(default='Do it yourself!', max_length=150)),
    #             ('link', models.URLField()),
    #         ],
    #     ),
    #     migrations.AddField(
    #         model_name='beginner',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='binary',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='brain',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='brute',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='dp',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='dpstand',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='dsu',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='graph',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='greed',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='hash',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='implement',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='pair',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='pointer',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='segtree',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='sort',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='sub',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AddField(
    #         model_name='tree',
    #         name='order',
    #         field=models.CharField(default='1', max_length=20),
    #     ),
    #     migrations.AlterField(
    #         model_name='beginner',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='binary',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='brain',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='brute',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='dp',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='dpstand',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='dsu',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='graph',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='greed',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='hash',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='implement',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='pair',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='pointer',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='segtree',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='sort',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='sub',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    #     migrations.AlterField(
    #         model_name='tree',
    #         name='description',
    #         field=models.TextField(default='Do it yourself!', max_length=150),
    #     ),
    # ]
