# Generated by Django 3.2.19 on 2023-07-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20230705_1643'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='add',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='add',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='beginner',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='beginner',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='binary',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='binary',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='bit',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='bit',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='brain',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='brain',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='brute',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='brute',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='dp',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='dp',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='dpstand',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='dpstand',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='dsu',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='dsu',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='graph',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='graph',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='greed',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='greed',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='hash',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='hash',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='implement',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='implement',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='mixed',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='mixed',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='pair',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='pair',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='pointer',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='pointer',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='segtree',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='segtree',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='sort',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='sort',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='sub',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.TextField(default='Do it yourself!', max_length=250),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=90),
        ),
    ]
